# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/', verbose_name='Imagen'),
        ),
    ]
