# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.SmallIntegerField(default=1),
        ),
    ]
