# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacion',
            name='latitud',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='longitud',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
