# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20160612_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='tiendas',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='stores/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='tiendas',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telefono'),
        ),
    ]
